
- name: create topics
  shell: |
    /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --create --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }} --replication-factor {{ item.replication_factor }} || true
  with_items: "{{processing_kafka_topics}}"
  ignore_errors: true
  when: kafka_id=="1"
  tags:
    - processing-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{processing_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined  
  tags:
    - processing-kafka

- name: overriding default partition size
  shell: "/opt/kafka/bin/kafka-topics.sh  --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{item}} --config max.message.bytes={{kafka_partition_override_size}}"
  with_items:
    - "{{env}}.telemetry.ingest"
    - "{{env}}.telemetry.extractor.failed"

- name: overriding data pipeline downstream topic size
  shell: "/opt/kafka/bin/kafka-topics.sh  --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{item}} --config max.message.bytes={{dp_downstream_kafka_max_message_bytes}}"
  with_items:
    - "{{env}}.telemetry.duplicate"
    - "{{env}}.telemetry.failed"
