---

- name: Download backup file
  shell: "az storage blob download --container-name {{ redis_backup_azure_container_name }} --file {{ redis_restore_file_name }} --name {{ redis_restore_file_name }} --account-name {{sunbird_management_storage_account_name}} --account-key {{sunbird_management_storage_account_key}}"
  args:
    chdir: /tmp/ 

- name: stop redis to take backup 
  become: yes
  systemd:
    name: redis
    state: stopped

- name: Copy rdb file to data dir
  shell: cp /tmp/{{ redis_restore_file_name }} {{ analytics_user_home }}/redis-stable/dump.rdb

- name: start redis backup
  become: yes
  systemd:
    name: redis
    state: started

- name: Keyspace info
  shell: "echo info keyspace | ./src/redis-cli"
  register: restoreinfo
  args:
    chdir: "{{analytics_user_home}}/redis-stable/"

- debug: var=restoreinfo.stdout_lines
