remote_user: druid
remote_group: users
broker_port: 8082
druid_home: /home/druid
desktop_pdata_id: "{{env}}.sunbird.desktop"

druid_mm_heap_dump_file: /var/log/druid/crash_logs/middlemanager.hprof

druid_overlord_port: 8090

ingestion_spec_configs:
  raw_telemetry_events:
    minTaskMemory: 512m
    maxTaskMemory: 1024m
    maxDirectTaskMemory: 1024m

raw_offline_desktop_taskcount: 1
raw_summary_events_taskcount: 1
raw_telemetry_events_taskcount: 1
raw_cb_audit_events_taskcount: 1
raw_dashboards_user_course_progress_taskcount: 1
raw_dashboards_course_competency_taskcount: 1
raw_dashboards_course_rating_summary_taskcount: 1
raw_dashboards_declared_user_competency_taskcount: 1
raw_dashboards_expected_user_competency_taskcount: 1
raw_dashboards_frac_competency_taskcount: 1
raw_dashboards_user_competency_gap_taskcount: 1
raw_telemetry_feedback_events_taskcount: 1
rollup_error_hourly_syncts_taskcount: 1
rollup_summary_distinct_counts_taskcount: 1
rollup_summary_syncts_taskcount: 1
rollup_telemetry_audit_syncts_taskcount: 1
rollup_telemetry_hourly_syncts_taskcount: 1
rollup_telemetry_syncts_taskcount: 1
rollup_tpd_hourly_taskcount: 1
sl_survey_evidence_task_count: 1
sl_observation_task_count: 1
sl_observation_evidence_task_count: 1
sl_survey_task_count: 1
rollup_course_completion_audit_syncts_taskcount: 1 
