apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jobmanager
  labels:
    app: flink
    component: {{ .Release.Name }}-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
  - name: ui
    port: 8081
{{- $job-config-key := .Release.Name }}
    nodePort: {{ index .Values $job-config-key.job_nodeport }}
  
  selector:
    app: flink
    component: {{ .Release.Name }}-jobmanager
