## This file contains alert rules related vars
prometheus_rule_selector_app: prometheus-operator
prometheus_rule_selector_release: prometheus-operator
fullnameOverride: sunbird-monitoring
namespace: monitoring

# Node Exporter vars
node_cpu_usage_percentage_threshold_Warning: 80
node_cpu_usage_percentage_threshold_Critical: 90
node_cpu_usage_percentage_threshold_Fatal: 95
node_memory_usage_percentage_threshold_Critical: 90
node_memory_usage_percentage_threshold_Warning: 80
node_memory_usage_percentage_threshold_Fatal: 95
node_load_avg_threshold_Critical: 90
node_load_avg_threshold_Warning: 80
node_load_avg_threshold_Fatal: 95
node_disk_usage_percentage_threshold_Warning: 80
node_disk_usage_percentage_threshold_Critical: 90
node_disk_usage_percentage_threshold_Fatal: 95

# DP Jobs lag vars critical
cb_preprocessor_threshold_critical: {{ cb_preprocessor_threshold_critical }}

# DP Jobs lag vars warning
cb_preprocessor_threshold_warning: {{ cb_preprocessor_threshold_warning }}

# Checkpoint failure vars
cb_preprocessor_checkpointfailure_threshold_critical: {{ cb_preprocessor_checkpointfailure_threshold_critical }}

flink_job_names:
  cb-preprocessor: {{ cb_preprocessor_threshold_critical }}

nginx_tps_threshold: {{ nginx_tps_threshold }} # being used in flink jobs percentage lag alertrules
flink_lag_percentage_threshold: {{ flink_lag_percentage_threshold }} # being used in flink jobs percentage lag alertrules
flink_lag_offset_duration: {{ flink_lag_offset_duration }} # values in mins.  offset time window to compare the metrics between current metrics and last 30(example) minutes. 

pv_usage_threshold_critical: {{ pv_usage_threshold_critical }}
