env: dev
kafka_partition_override_size: 5242880
dp_downstream_kafka_max_message_bytes: 1572864

processing_kafka_overriden_topics:
  - name: telemetry.duplicate
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.failed
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.cb.audit
    retention_time: 172800000
    replication_factor: 1
  - name: druid.cb.audit
    retention_time: 172800000
    replication_factor: 1
  - name: druid.cb.work.order.row
    retention_time: 172800000
    replication_factor: 1
  - name: druid.cb.work.order.officer
    retention_time: 172800000
    replication_factor: 1


processing_kafka_topics:
  - name: telemetry.duplicate
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.cb.audit
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.cb.audit
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.cb.work.order.row
    num_of_partitions: 1
    replication_factor: 1
  - name: druid.cb.work.order.officer
    num_of_partitions: 1
    replication_factor: 1
